#!/bin/bash

set -eou pipefail

./word_tokenize.py > news.tok
ngramsymbols news.tok news.sym
farcompilestrings \
    --fst_type=compact \
    --symbols=news.sym \
    news.tok - |
  ngramcount \
      --order=3 \
      - - | \
   ngrammake \
      --method=kneser_ney \
      - - | \
   ngramshrink \
      --method=relative_entropy \
      --target_number_of_ngrams=10000000 \
      - word.lm
echo "LM size:"
ngraminfo word.lm
